language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: COMPOSER_FLAGS="--dev"
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--dev"
    allow_failures:
        - php: 7.1
        - php: hhvm-nightly

install:
    - composer update $COMPOSER_FLAGS --no-interaction -v
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.12.1/php-cs-fixer.phar -o php-cs-fixer.phar; fi

script:
    - if [[ $TRAVIS_PHP_VERSION = 5.3 ]]; then phpunit --verbose --testsuite "5.3.6"; else phpunit --verbose; fi
    - phpenv config-rm xdebug.ini || return 0
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run -v --config-file=.php_cs fix; fi
