language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable --optimize-autoloader"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --optimize-autoloader"
        - php: nightly
          env: COMPOSER_FLAGS="--dev"
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--dev --optimize-autoloader"
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

install:
    - composer update $COMPOSER_FLAGS --no-interaction -v
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.3.2/php-cs-fixer.phar -o php-cs-fixer.phar; fi

script:
    - chmod 755 tests/assets/dir
    - chmod 644 tests/assets/dir/test_file.txt
    - phpenv config-rm xdebug.ini || return 0
    - vendor/bin/phpunit --verbose
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run -vvv fix; fi
